name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy build files to EC2
      run: |
        scp -r ./dist/* uubuntu@${{ secrets.EC2_HOST }}:/var/www/html/
      env:
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

    - name: Restart nginx on EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'
      env:
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
